language: go

go:
  - 1.9.x
  - tip

git:
  depth: 1

addons:
  apt:
    packages:
      - rabbitmq-server

services:
  - rabbitmq

before_install:
  - go get -v ./...
  - go mod vendor

notifications:
  email: false

script:
  - rabbitmqctl add_user local local
  - rabbitmqctl set_user_tags local administrator
  - rabbitmqctl set_permissions -p / local ".*" ".*" ".*"
  - go run ./cmd -mode test -migrate -reset
  - go test -v -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
