language: go

go:
  - 1.11.x

env:
  - GO111MODULE=on

git:
  depth: 1

addons:
  postgresql: "11"
  apt:
    packages:
      - rabbitmq-server
      - postgresql-11
      - postgresql-client-11

services:
  - rabbitmq
  - postgresql

before_install:
  - sudo rabbitmqctl add_user local local
  - sudo rabbitmqctl set_user_tags local administrator
  - sudo rabbitmqctl set_permissions -p / local ".*" ".*" ".*"
  - go get -t -v ./...
  - go mod vendor

notifications:
  email: false

before_script:
  - psql -c "create user agente login password '123456';" -U postgres
  - psql -c "create database agente_test owner agente;" -U postgres

script:
  - go run ./cmd -mode test -migrate -reset
  - go test -v -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
